#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://121.89.220.143:1433;databaseName=MSSqlKCContext
    username: sa
    password: Hcqqkeum+lPvQlPHyHOhM33xffnXWK2P
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    
GlobalConfig:
  EncryptKey: KCloudy-Microsoft-EncryptKey

  SSOWebDomain: http://sso.kcloudy.com/
  ResWebDomain: http://resource.kcloudy.com/
  CfgWebDomain: http://subdomain.cfg.kcloudy.com/
