server:
  port: 4002
  tomcat:
    uri-encoding: UTF-8
    max-connections: 3000
    max-threads: 1000
  max-http-header-size: 1024000

spring:
  profiles:
    active: dev
  application:
    name: 网站管理接口
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024000
  devtools:
    restart:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: kc.database.core.CustomSqlServer2012Dialect
        format_sql: true
        hbm2ddl:
          auto: none
        multiTenancy: SCHEMA
        multi_tenant_connection_provider: kc.database.multitenancy.MsSqlMultiTenantConnectionProviderImpl
        tenant_identifier_resolver: kc.database.multitenancy.MultiTenantIdentifierResolver
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
  output:
    ansi:
      enabled: DETECT
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

logging:
  charset:
    console: UTF-8
  file:
    charset: UTF-8
  level:
    org.springframework.boot.autoconfigure: ERROR

GlobalConfig:
  ApplicationId: AD401D87-0F1C-46DE-AE3E-BE4EC1C57D2C
  EncryptKey: KCloudy-Microsoft-EncryptKey

  SSOWebDomain: https://sso.kcloudy.com/
  ResWebDomain: https://resource.kcloudy.com/
  AccWebDomain: https://subdomain.acc.kcloudy.com/

  ClientId: CFWinAPP
  ClientSecret: app_password
  TempFilePath: /tmp,
  UploadConfig:
    ImageMaxSize: 20
    ImageExt: jpg,jpeg,png,gif,bmp
    FileMaxSize: 20
    FileExt: txt,doc,docx,xls,xlsx,ppt,pptx,pdf

swagger:
  clientId: Y0RiYQ==
  clientSecret: MmJmNWIyM2Q5ZjY4OWU5YzFmYWVkZTUwNzY2ZWJkNTg=
  title: 网站管理接口接口
  description: 网站管理接口接口
