
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('Organizatio', 1, 1, 999999999, 1, 'ORG', NULL, '组织ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('Member', 1, 1, 999999999, 1, 'USR', NULL, '用户ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('BusinessType', 1, 1, 999999999, 1, 'BUT', NULL, '业务类型ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('Customer', 1, 1, 999999999, 1, 'CUR', NULL, '客户ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('Supplier', 1, 1, 999999999, 1, 'SUP', NULL, '供应商ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('OfferingProvider', 1, 1, 999999999, 1, 'OPS', NULL, '商品模板ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('Offering', 1, 1, 999999999, 1, 'OFR', NULL, '商品ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('OrderOffering', 1, 1, 999999999, 1, 'OOR', NULL, '订单ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('MessageTemplate', 1, 1, 999999999, 1, 'MGT', NULL, '消息模板ID', '2018-12-01');
INSERT INTO `cTest`.`sys_SysSequence` (`SequenceName`, `CurrentValue`, `InitValue`, `MaxValue`, `StepValue`, `PreFixString`, `PostFixString`, `Comments`, `CurrDate`) VALUES ('Config', 1, 1, 999999999, 1, 'CFG', NULL, '配置ID', '2018-12-01');
