server:
  port: 2001
  tomcat:
    uri-encoding: UTF-8
    max-connections: 3000
    max-threads: 1000
  max-http-header-size: 1024000
spring:
  application:
    name: 账户管理
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024000
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: kc.database.core.CustomSqlServer2012Dialect
        format_sql: true
        hbm2ddl:
          auto: none
        multiTenancy: SCHEMA
        multi_tenant_connection_provider: kc.database.multitenancy.MsSqlMultiTenantConnectionProviderImpl
        tenant_identifier_resolver: kc.database.multitenancy.MultiTenantIdentifierResolver
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: DETECT
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
logging:
  charset:
    console: UTF-8
  file:
    charset: UTF-8
  level:
    org.springframework.boot.autoconfigure: ERROR

GlobalConfig:
  ApplicationId: 45672506-DDB7-4D57-AD44-BD0AB136B556
  EncryptKey: KCloudy-Microsoft-EncryptKey

  SSOWebDomain: https://sso.kcloudy.com/
  ResWebDomain: https://resource.kcloudy.com/
  AccWebDomain: https://subdomain.acc.kcloudy.com/

  ClientId: CFWinAPP
  ClientSecret: app_password
  TempFilePath: /tmp,
  WeixinAppKey:
  WeixinAppSecret:
  WeixinAppToken:
  UploadConfig:
    ImageMaxSize: 20
    ImageExt: jpg,jpeg,png,gif,bmp
    FileMaxSize: 20
    FileExt: txt,doc,docx,xls,xlsx,ppt,pptx,pdf
