#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: false
  datasource: #数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://121.89.220.143:1433;databaseName=MSSqlKCContext
    username: sa
    password: Hcqqkeum+lPvQlPHyHOhM33xffnXWK2Pncs
logging:
  level:
    org.springframework.boot.autoconfigure: INFO
    
GlobalConfig:
  EncryptKey: KCloudy-Microsoft-EncryptKey

  SSOWebDomain: http://sso.kcloudy.com/
  ResWebDomain: http://resource.kcloudy.com/
  CodeWebDomain: http://subdomain.code.kcloudy.com/
